### ISSUE TITLE
images for README

### ISSUE THREAD

**Issue by Abhijjith** [Abhijjith/Abhijjith.github.io#1]
![screenshot_2015-05-28-13-44-42](https://cloud.githubusercontent.com/assets/11919615/7862353/f1254cfc-0572-11e5-801f-e6eb0f61fc1e.png)
![screenshot_2015-05-28-13-45-23](https://cloud.githubusercontent.com/assets/11919615/7862369/07de1d7a-0573-11e5-81b2-5b8069c8c605.png)
![screenshot_2015-05-28-19-15-58](https://cloud.githubusercontent.com/assets/11919615/7862377/12cd6646-0573-11e5-99c6-9d2b76f3af24.png)

**Comment by Mindstormer619** [comment]
Why is this an issue?

**Comment by Abhijjith** [comment]
I'm presently editing my readme file in the markdown format.
Including the images of screenshots

**Comment by Abhijjith** [comment]
I googled up and saw that i can upload the images to issue and then copy the url of the images to my readme file.

**Comment by Mindstormer619** [comment]
You can also upload your images elsewhere. http://imgur.com/ or http://postimage.org/ are appropriate. No need for an issue in this.

**Comment by Abhijjith** [comment]
Ohh okay okay. Thanks for the info :) So shall i remove this issue ?

**Comment by Mindstormer619** [comment]
Close it, yes.

**Comment by Mindstormer619** [comment]
You can also upload your images elsewhere. imgur.com or postimage,org are appropriate. No need for an issue in this.
